-- +goose Up
CREATE TABLE training_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id     BIGINT NOT NULL,
    params JSONB NOT NULL
);

-- +goose Down
DROP TABLE training_items;
