-- +goose Up
CREATE TABLE templates (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type        TEXT NOT NULL,
    name        TEXT NOT NULL,
    description TEXT NOT NULL,
    video_links  TEXT[]
);

-- +goose Down
DROP TABLE templates;
