-- +goose Up
CREATE TABLE trainings (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date              TIMESTAMPTZ NOT NULL,
    comment           TEXT NOT NULL,
    result            TEXT,
    result_files TEXT[]
);

CREATE INDEX trainings_date_idx
    ON trainings (date);

-- +goose Down
DROP TABLE trainings;
